<?php

$packageJson = json_decode(file_get_contents(__DIR__ . '/package.json'), true);

$commands = array_map(fn($c) => $c['command'], $packageJson['contributes']['commands'] ?? []);

$commands[] = 'laravel.open';

file_put_contents(__DIR__ . '/src/commands/generatedRegisteredCommands.ts',
    "// This file is auto-generated by 'generate-registered-commands.php'. Do not edit directly.\n" .
    "// Run 'php generate-registered-commands.php' to regenerate.\n\n" .
    "export type RegisteredCommand = \"" . implode('" | "', $commands) . "\";\n"
);

exec('npm run format');
