import fs from "fs";
import path from "path";
import { config } from "@src/support/config";
import { loadAndWatch } from "@src/support/fileWatcher";
import { runInLaravel, template } from "@src/support/php";
import { projectPath } from "@src/support/project";
import { indent } from "@src/support/util";

export interface PestConfig {
    uses: PestUse[];
    expectations: PestExpectation[];
}

export interface PestUse {
    path: string;
    classes: string[];
    traits: string[];
}

export interface PestExpectation {
    name: string;
    parameters: string;
}

export const registerPestHelper = () => {
    if (!config("pest.generateDocBlocks", true)) {
        return;
    }

    loadAndWatch(
        () => {
            runInLaravel<PestConfig | null>(template("pest"))
                .then(writePestDocBlocks)
                .catch(console.error);
        },
        "tests/**/*",
        ["create", "delete", "change"],
    );
};

const writePestDocBlocks = (pest: PestConfig | null): void => {
    if (!pest || (!pest.uses.length && !pest.expectations.length)) {
        return;
    }

    const content = renderPestDocBlockFile([
        renderFunctionStub(pest.uses),
        ...renderVirtualTestCases(pest.uses),
        ...renderExpectations(pest.expectations),
    ]);

    const pestFilePath = projectPath("storage/framework/testing/_pest.php");

    fs.mkdirSync(path.dirname(pestFilePath), { recursive: true });
    fs.writeFileSync(pestFilePath, content);
};

const renderFunctionStub = (uses: PestUse[]): string => {
    const unionType = [
        ...new Set(
            uses.flatMap((use) => {
                const baseClass =
                    use.classes[0] ?? "PHPUnit\\Framework\\TestCase";

                const baseType = baseClass.startsWith("\\")
                    ? baseClass
                    : `\\${baseClass}`;

                return use.traits.length
                    ? [baseType, `\\${pestNamespace(use.path)}\\TestCase`]
                    : [baseType];
            }),
        ),
    ].join("|");

    return `namespace {

    /**
     * Runs the given closure before all tests in the current file.
     *
     * @param-closure-this ${unionType}  $closure
     */
    function beforeAll(Closure $closure): void {}

    /**
     * Runs the given closure before each test in the current file.
     *
     * @param-closure-this ${unionType}  $closure
     */
    function beforeEach(?Closure $closure = null): \\Pest\\PendingCalls\\BeforeEachCall {}

    /**
     * Runs the given closure after each test in the current file.
     *
     * @param-closure-this ${unionType}  $closure
     */
    function afterEach(?Closure $closure = null): \\Pest\\PendingCalls\\AfterEachCall {}

    /**
     * Runs the given closure after all tests in the current file.
     *
     * @param-closure-this ${unionType}  $closure
     */
    function afterAll(Closure $closure): void {}

    /**
     * Adds the given closure as a test.
     *
     * @param-closure-this ${unionType}  $closure
     */
    function test(?string $description = null, ?Closure $closure = null): \\Pest\\Support\\HigherOrderTapProxy|\\Pest\\PendingCalls\\TestCall {}

    /**
     * Adds the given closure as a test.
     *
     * @param-closure-this ${unionType}  $closure
     */
    function it(string $description, ?Closure $closure = null): \\Pest\\PendingCalls\\TestCall {}

}`;
};

const renderVirtualTestCases = (uses: PestUse[]): string[] => {
    return uses.flatMap((use) => {
        if (!use.traits.length) {
            return [];
        }

        const traitUses = use.traits
            .map((trait) => indent(`use \\${trait};`, 2))
            .join("\n");

        return [
            `namespace ${pestNamespace(use.path)} {

    class TestCase {
${traitUses}
    }

}`,
        ];
    });
};

const renderExpectations = (expectations: PestExpectation[]): string[] => {
    if (!expectations.length) {
        return [];
    }

    const methods = expectations
        .map(({ name, parameters }) =>
            indent(` * @method self ${name}(${parameters})`),
        )
        .join("\n");

    return (
        [
            ["Pest", "Expectation"],
            ["Pest\\Expectations", "OppositeExpectation"],
        ] as const
    ).map(
        ([namespace, className]) => `namespace ${namespace} {

    /**
${methods}
     */
    class ${className} {}

}`,
    );
};

const renderPestDocBlockFile = (blocks: string[]): string => {
    const header = [
        `<?php`,
        ``,
        `/**`,
        ` * This file is auto-generated by the Laravel VS Code extension.`,
        ` * Do not modify this file directly as your changes will be overwritten.`,
        ` */`,
    ].join("\n");

    return [header, ...blocks].join("\n\n");
};

const pestNamespace = (filePath: string): string => {
    const relative = filePath.replace(/^tests[/\\]?/, "");
    const segment = relative ? relative.replace(/[/\\]/g, "\\") : "Global";
    return `_Pest\\${segment}`;
};
