// This file is auto-generated by 'generate-registered-commands.php'. Do not edit directly.
// Run 'php generate-registered-commands.php' to regenerate.

export type RegisteredCommand =
    | "laravel.pint.run"
    | "laravel.pint.runOnDirtyFiles"
    | "laravel.pint.runOnCurrentFile"
    | "laravel.wrapWithHelper"
    | "laravel.wrapWithHelper.unwrap"
    | "laravel.wrapWithHelper.dd"
    | "laravel.wrapWithHelper.dump"
    | "laravel.wrapWithHelper.collect"
    | "laravel.wrapWithHelper.str"
    | "laravel.refactorSelectedHtmlClassToBladeDirective"
    | "laravel.refactorAllHtmlClassesToBladeDirectives"
    | "laravel.open";
