name: Publish VS Code Extension with Changelog Update

on:
    release:
        types: [created]

permissions:
  contents: write

jobs:
    update_changelog:
        uses: laravel/.github/.github/workflows/update-changelog.yml@9c15e86fffce728fb6c50ebeae24fd63e98f4d1d # main
        permissions:
            contents: write

    publish:
        runs-on: ubuntu-latest
        needs: update_changelog
        steps:
            - name: Checkout code
              uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
              with:
                persist-credentials: false

            - name: Set up Node.js
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Publish Extension
              env:
                  VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
              run: npx vsce publish -p $VSCE_TOKEN --no-git-tag-version
