name: Publish VS Code Extension with Changelog Update

on:
    release:
        types: [created]

permissions:
  contents: write

jobs:
    update_changelog:
        uses: laravel/.github/.github/workflows/update-changelog.yml@9c15e86fffce728fb6c50ebeae24fd63e98f4d1d # main
        permissions:
            contents: write

    publish:
        runs-on: ubuntu-latest
        needs: update_changelog
        steps:
            - name: Checkout code
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
              with:
                persist-credentials: false

            - name: Set up Node.js
              uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Publish Extension
              env:
                  VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
              run: npx vsce publish -p $VSCE_TOKEN --no-git-tag-version
