name: Publish VS Code Extension with Changelog Update

on:
    release:
        types: [created]

jobs:
    update_changelog:
        if: ${{ !github.event.release.prerelease }}
        uses: laravel/.github/.github/workflows/update-changelog.yml@main
        permissions:
            contents: write

    publish:
        runs-on: ubuntu-latest
        needs: update_changelog
        if: ${{ !github.event.release.prerelease }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Publish Extension
              env:
                  VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
              run: npx vsce publish -p $VSCE_TOKEN --no-git-tag-version

    publish_prerelease:
        runs-on: ubuntu-latest
        if: ${{ github.event.release.prerelease }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Publish Pre-Release Extension
              env:
                  VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
              run: npx vsce publish --pre-release -p $VSCE_TOKEN --no-git-tag-version
